export const CATEGORIES = {
  '3d':          { label: '3D e Animação',              icon: '⬡' },
  audiovisual:   { label: 'Audiovisual',                icon: '🎬' },
  design:        { label: 'Design',                     icon: '◼' },
  musica:        { label: 'Música e Áudio',             icon: '🎵' },
  texto:         { label: 'Texto e Escrita',            icon: '📝' },
  codigo:        { label: 'Código e Tecnologia',        icon: '💻' },
  arquitetura:   { label: 'Arquitetura e Engenharia',   icon: '🏗' },
  arte:          { label: 'Arte e Artesanato',          icon: '🎨' },
  saude:         { label: 'Educação Física e Saúde',    icon: '🏃' },
  linguas:       { label: 'Línguas e Acessibilidade',   icon: '🌐' },
  outros:        { label: 'Outros',                     icon: '📐' },
};

export const TYPES = {
  // 3D e Animação
  modelagem:        { label:'Modelagem 3D',           cat:'3d',          input:'obj',
    hint: 'Envie o arquivo .obj e/ou imagens do trabalho — combinando os dois a avaliação fica mais completa.',
    criteria:[{name:'Topologia / Edge Flow',w:3},{name:'Proporção e Forma',w:3},{name:'Limpeza (N-gons)',w:2},{name:'Complexidade Técnica',w:1},{name:'Organização',w:1}] },
  animacao:         { label:'Animação 3D',             cat:'3d',          input:'video',
    hint: 'Envie o vídeo da animação (MP4, MOV) e/ou frames-chave como imagem. A IA analisa timing, arcos e fluidez do movimento.',
    criteria:[{name:'Timing e Spacing',w:3},{name:'Arcos de Movimento',w:3},{name:'Squash & Stretch',w:2},{name:'Antecipação',w:2},{name:'Follow-through',w:2}] },
  animacao_2d:      { label:'Animação 2D',             cat:'3d',          input:'video',
    hint: 'Envie o vídeo da animação 2D (MP4, MOV) e/ou frames exportados. A IA analisa timing, fluidez e princípios de animação.',
    criteria:[{name:'Timing e Spacing',w:3},{name:'Fluidez do Movimento',w:3},{name:'Expressividade',w:2},{name:'Antecipação e Reação',w:2},{name:'Limpeza do Traço',w:2}] },
  rigging:          { label:'Rigging',                 cat:'3d',          input:'video',
    hint: 'Envie um vídeo do rig em movimento, imagens de poses-chave, ou ambos — combinando os dois a avaliação fica mais completa.',
    criteria:[{name:'Estrutura dos Ossos',w:3},{name:'Pesos de Deformação',w:3},{name:'Controladores',w:2},{name:'Hierarquia',w:2},{name:'Nomeação',w:1}] },
  texturizacao:     { label:'Texturização',            cat:'3d',          input:'img',
    hint: 'Envie renders com os materiais aplicados. Pode incluir o mapa UV ou texturas separadas para análise completa.',
    criteria:[{name:'Qualidade do Unwrap',w:3},{name:'Resolução e Detalhes',w:3},{name:'Coerência Visual',w:2},{name:'Materiais PBR',w:2},{name:'Seamless (costuras)',w:2}] },
  iluminacao:       { label:'Iluminação 3D',           cat:'3d',          input:'img',
    hint: 'Envie o render com a iluminação aplicada. Pode incluir versões diferentes para comparação de setup de luz.',
    criteria:[{name:'Qualidade das Sombras',w:3},{name:'Contraste e Exposição',w:3},{name:'Temperatura de Cor',w:2},{name:'Luz de Preenchimento',w:2},{name:'Realismo',w:2}] },
  render:           { label:'Render',                  cat:'3d',          input:'img',
    hint: 'Envie a imagem do render final. Pode incluir múltiplos renders ou variações para uma avaliação mais completa.',
    criteria:[{name:'Qualidade Visual Geral',w:3},{name:'Materiais e Texturas',w:3},{name:'Iluminação',w:2},{name:'Composição',w:2},{name:'Pós-processamento',w:1}] },
  vfx:              { label:'VFX / Efeitos Visuais',   cat:'3d',          input:'video',
    hint: 'Envie o vídeo com os efeitos aplicados. Inclua se possível a cena sem o efeito para comparação.',
    criteria:[{name:'Qualidade Visual do Efeito',w:3},{name:'Integração com a Cena',w:3},{name:'Realismo e Coerência',w:2},{name:'Técnica Utilizada',w:2},{name:'Acabamento Final',w:2}] },
  simulacao:        { label:'Simulação',               cat:'3d',          input:'video',
    hint: 'Envie o vídeo da simulação rodando (tecido, fluido, partículas, etc.). A IA avalia a coerência física e o realismo do movimento.',
    criteria:[{name:'Coerência Física',w:3},{name:'Realismo do Movimento',w:3},{name:'Parâmetros de Colisão',w:2},{name:'Estabilidade da Simulação',w:2},{name:'Acabamento Visual',w:2}] },

  // Audiovisual
  storyboard:       { label:'Storyboard',              cat:'audiovisual', input:'imgs',
    hint: 'Envie as pranchas do storyboard como imagem (digitalizado ou digital). Envie múltiplas imagens para cobrir toda a sequência.',
    criteria:[{name:'Sequência Narrativa',w:3},{name:'Clareza dos Planos',w:3},{name:'Linguagem Cinematográfica',w:2},{name:'Expressão dos Personagens',w:2},{name:'Indicações Técnicas',w:1}] },
  edicao_video:     { label:'Edição de Vídeo',         cat:'audiovisual', input:'video',
    hint: 'Envie o vídeo editado. A IA analisa ritmo de cortes, transições, narrativa visual e coerência da montagem.',
    criteria:[{name:'Ritmo e Fluidez dos Cortes',w:3},{name:'Narrativa Visual',w:3},{name:'Transições',w:2},{name:'Sincronia com Áudio',w:2},{name:'Acabamento Técnico',w:2}] },
  motion_graphics:  { label:'Motion Graphics',         cat:'audiovisual', input:'video',
    hint: 'Envie o vídeo do motion graphics (MP4, MOV). A IA avalia animação, design e comunicação visual.',
    criteria:[{name:'Qualidade da Animação',w:3},{name:'Design e Composição Visual',w:3},{name:'Timing e Ritmo',w:2},{name:'Coerência com a Identidade',w:2},{name:'Acabamento Técnico',w:2}] },
  colorgrading:     { label:'Color Grading',           cat:'audiovisual', input:'video',
    hint: 'Envie o vídeo com o color grading aplicado. Inclua se possível uma cena sem tratamento para comparação.',
    criteria:[{name:'Consistência das Cores',w:3},{name:'Adequação ao Estilo / Narrativa',w:3},{name:'Contraste e Exposição',w:2},{name:'Skin Tones (se houver)',w:2},{name:'Acabamento Final',w:2}] },
  apresentacao_oral:{ label:'Apresentação Oral',       cat:'audiovisual', input:'video',
    hint: 'Envie o vídeo (MP4, MOV) ou apenas o áudio (MP3, WAV, M4A). A IA analisa clareza, postura, dicção, organização do conteúdo e domínio do tema.',
    criteria:[{name:'Clareza e Organização',w:3},{name:'Domínio do Conteúdo',w:3},{name:'Dicção e Comunicação',w:2},{name:'Postura e Linguagem Corporal',w:2},{name:'Tempo e Ritmo',w:2}] },
  locucao:          { label:'Locução / Dublagem',      cat:'audiovisual', input:'video',
    hint: 'Envie o vídeo (MP4, MOV) ou apenas o áudio (MP3, WAV, M4A). A IA avalia dicção, entonação, ritmo e adequação ao contexto.',
    criteria:[{name:'Dicção e Clareza',w:3},{name:'Entonação e Expressividade',w:3},{name:'Ritmo e Pausas',w:2},{name:'Adequação ao Contexto',w:2},{name:'Naturalidade',w:2}] },

  // Design
  design_grafico:   { label:'Design Gráfico',          cat:'design',      input:'img',
    hint: 'Envie a peça gráfica finalizada (PNG, JPG). Pode incluir variações, versões ou detalhes relevantes.',
    criteria:[{name:'Composição e Hierarquia',w:3},{name:'Tipografia',w:3},{name:'Paleta de Cores',w:2},{name:'Conceito e Ideia',w:2},{name:'Acabamento Técnico',w:2}] },
  ilustracao:       { label:'Ilustração Digital',      cat:'design',      input:'img',
    hint: 'Envie a ilustração finalizada. Pode incluir estudos, rascunhos ou etapas do processo.',
    criteria:[{name:'Técnica de Desenho',w:3},{name:'Uso de Cor',w:3},{name:'Proporção e Anatomia',w:2},{name:'Estilo e Expressividade',w:2},{name:'Acabamento',w:2}] },
  ux_ui:            { label:'UX/UI Design',            cat:'design',      input:'img',
    hint: 'Envie prints das telas ou protótipo. Pode incluir múltiplas telas para mostrar o fluxo da interface.',
    criteria:[{name:'Usabilidade e Clareza',w:3},{name:'Consistência Visual',w:3},{name:'Hierarquia da Informação',w:2},{name:'Acessibilidade',w:2},{name:'Componentes e Grid',w:2}] },
  concept_art:      { label:'Concept Art',             cat:'design',      input:'img',
    hint: 'Envie as artes conceituais (personagem, cenário, objeto). Pode incluir variações e estudos de referência.',
    criteria:[{name:'Clareza do Conceito',w:3},{name:'Qualidade do Desenho',w:3},{name:'Coerência Visual',w:2},{name:'Variações e Alternativas',w:2},{name:'Apresentação',w:1}] },
  identidade_visual:{ label:'Identidade Visual',       cat:'design',      input:'img',
    hint: 'Envie as peças da identidade: logo, paleta, tipografia e aplicações. Múltiplas imagens são bem-vindas.',
    criteria:[{name:'Conceito e Originalidade',w:3},{name:'Consistência Visual',w:3},{name:'Tipografia',w:2},{name:'Paleta de Cores',w:2},{name:'Versatilidade das Aplicações',w:2}] },
  design_embalagem: { label:'Design de Embalagem',     cat:'design',      input:'img',
    hint: 'Envie renders ou fotos da embalagem finalizada. Inclua diferentes ângulos e aberta/fechada se possível.',
    criteria:[{name:'Conceito e Identidade',w:3},{name:'Hierarquia Visual',w:3},{name:'Ergonomia e Funcionalidade',w:2},{name:'Materiais e Produção',w:2},{name:'Acabamento',w:2}] },
  tipografia:       { label:'Tipografia',              cat:'design',      input:'img',
    hint: 'Envie a família tipográfica ou composição tipográfica. Pode incluir detalhes de glyphs e aplicações.',
    criteria:[{name:'Legibilidade',w:3},{name:'Coerência dos Caracteres',w:3},{name:'Espaçamento e Kerning',w:2},{name:'Expressividade',w:2},{name:'Versatilidade',w:2}] },
  fotografia:       { label:'Fotografia',              cat:'design',      input:'img',
    hint: 'Envie a fotografia em boa resolução. Pode incluir série fotográfica ou fotos alternativas para contextualizar.',
    criteria:[{name:'Exposição e Luminosidade',w:3},{name:'Composição e Enquadramento',w:3},{name:'Foco e Nitidez',w:2},{name:'Narrativa Visual',w:2},{name:'Pós-processamento',w:1}] },
  moda:             { label:'Design de Moda',          cat:'design',      input:'img',
    hint: 'Envie o croqui ou ficha técnica digitalizada. Pode incluir detalhes de tecido, estampas e acabamentos.',
    criteria:[{name:'Conceito e Identidade',w:3},{name:'Ficha Técnica',w:3},{name:'Proporções e Silhueta',w:2},{name:'Escolha de Materiais',w:2},{name:'Apresentação Visual',w:1}] },

  // Música e Áudio
  musica_partitura: { label:'Partitura',               cat:'musica',      input:'imgs',
    hint: 'Envie a partitura digitalizada ou exportada como imagem. Envie múltiplas imagens para partituras com várias páginas.',
    criteria:[{name:'Harmonia e Progressão',w:3},{name:'Melodia',w:3},{name:'Ritmo e Métrica',w:2},{name:'Estrutura da Composição',w:2},{name:'Notação Musical',w:2}] },
  composicao_audio: { label:'Composição em Áudio',     cat:'musica',      input:'video',
    hint: 'Envie o áudio (MP3, WAV, M4A) ou vídeo (MP4, MOV) da composição. A IA analisa harmonia, melodia, ritmo e estrutura musical.',
    criteria:[{name:'Harmonia e Progressão de Acordes',w:3},{name:'Melodia',w:3},{name:'Ritmo e Groove',w:2},{name:'Estrutura da Composição',w:2},{name:'Originalidade',w:2}] },
  producao_musical: { label:'Produção Musical',        cat:'musica',      input:'video',
    hint: 'Envie o áudio (MP3, WAV, M4A) ou vídeo (MP4, MOV) da produção finalizada. A IA avalia mixagem, arranjo, balanço e qualidade sonora.',
    criteria:[{name:'Balanço e Mixagem',w:3},{name:'Qualidade Sonora Geral',w:3},{name:'Arranjo e Camadas',w:2},{name:'Dinâmica',w:2},{name:'Acabamento (mastering)',w:2}] },
  arranjo_musical:  { label:'Arranjo Musical',         cat:'musica',      input:'imgs',
    hint: 'Envie a partitura do arranjo como imagem. Pode incluir o áudio/vídeo de referência como arquivo adicional.',
    criteria:[{name:'Coerência Harmônica',w:3},{name:'Distribuição das Vozes',w:3},{name:'Uso dos Instrumentos',w:2},{name:'Dinâmica e Expressão',w:2},{name:'Fidelidade ao Original',w:2}] },
  sound_design:     { label:'Sound Design',            cat:'musica',      input:'video',
    hint: 'Envie o vídeo (MP4, MOV) com os sons aplicados, ou apenas o áudio (MP3, WAV). A IA avalia adequação, criatividade e qualidade dos efeitos sonoros.',
    criteria:[{name:'Adequação ao Contexto Visual',w:3},{name:'Criatividade e Originalidade',w:3},{name:'Qualidade Técnica',w:2},{name:'Sincronia',w:2},{name:'Coerência Geral',w:2}] },
  trilha_sonora:    { label:'Trilha Sonora',           cat:'musica',      input:'video',
    hint: 'Envie o vídeo com a trilha aplicada. A IA avalia como a música complementa e potencializa a narrativa visual.',
    criteria:[{name:'Adequação à Narrativa',w:3},{name:'Qualidade da Composição',w:3},{name:'Dinâmica Emocional',w:2},{name:'Timing e Sincronia',w:2},{name:'Originalidade',w:2}] },

  // Texto e Escrita
  redacao:          { label:'Redação / Artigo',        cat:'texto',       input:'text',
    hint: 'Cole o texto diretamente no campo abaixo. Pode incluir imagens de apoio se o trabalho tiver elementos visuais.',
    criteria:[{name:'Argumentação e Coerência',w:3},{name:'Estrutura do Texto',w:3},{name:'Gramática e Ortografia',w:2},{name:'Repertório e Referências',w:2},{name:'Conclusão',w:2}] },
  roteiro:          { label:'Roteiro',                 cat:'texto',       input:'text',
    hint: 'Cole o roteiro formatado no campo abaixo. Mantenha a formatação padrão de roteiro para uma análise mais precisa.',
    criteria:[{name:'Estrutura Dramática',w:3},{name:'Qualidade dos Diálogos',w:3},{name:'Desenvolvimento de Personagens',w:2},{name:'Formatação Técnica',w:2},{name:'Originalidade',w:2}] },
  tcc:              { label:'TCC / Monografia',        cat:'texto',       input:'text',
    hint: 'Cole o texto completo ou envie como .docx para avaliação de conteúdo. Para avaliar formatação ABNT, envie como imagem as páginas-chave: capa, folha de rosto, sumário, uma página de corpo e referências.',
    criteria:[{name:'Problema e Hipótese',w:3},{name:'Revisão Bibliográfica',w:3},{name:'Metodologia',w:2},{name:'Análise de Resultados',w:2},{name:'Normas ABNT',w:2}] },
  game_design:      { label:'Game Design Doc',         cat:'texto',       input:'text',
    hint: 'Cole o documento de game design. Pode incluir imagens de conceito, diagramas ou fluxos de gameplay.',
    criteria:[{name:'Clareza e Completude',w:3},{name:'Viabilidade do Conceito',w:3},{name:'Mecânicas de Jogo',w:3},{name:'Experiência do Jogador',w:2},{name:'Originalidade',w:2}] },
  copywriting:      { label:'Copywriting',             cat:'texto',       input:'text',
    hint: 'Cole o texto publicitário ou de marketing. Pode incluir a peça visual se houver.',
    criteria:[{name:'Persuasão e Impacto',w:3},{name:'Clareza da Mensagem',w:3},{name:'Adequação ao Público',w:2},{name:'Call to Action',w:2},{name:'Originalidade',w:2}] },
  poesia:           { label:'Poesia / Literatura',     cat:'texto',       input:'text',
    hint: 'Cole o texto literário ou poema no campo abaixo.',
    criteria:[{name:'Expressividade e Linguagem',w:3},{name:'Estrutura e Forma',w:3},{name:'Originalidade',w:2},{name:'Coerência Temática',w:2},{name:'Impacto Emocional',w:2}] },
  critica:          { label:'Crítica / Resenha',       cat:'texto',       input:'text',
    hint: 'Cole o texto da crítica ou resenha. Pode incluir imagem da obra analisada como referência.',
    criteria:[{name:'Fundamentação e Argumentação',w:3},{name:'Conhecimento do Tema',w:3},{name:'Estrutura do Texto',w:2},{name:'Imparcialidade',w:2},{name:'Qualidade da Escrita',w:2}] },

  // Código e Tecnologia
  programacao:      { label:'Programação',             cat:'codigo',      input:'text',
    hint: 'Cole o código-fonte diretamente. Pode incluir imagens do output ou prints do programa em execução.',
    criteria:[{name:'Lógica e Algoritmo',w:3},{name:'Boas Práticas',w:3},{name:'Legibilidade',w:2},{name:'Eficiência',w:2},{name:'Documentação',w:1}] },
  web:              { label:'HTML/CSS/JS',             cat:'codigo',      input:'text',
    hint: 'Cole o código HTML, CSS e/ou JavaScript. Pode incluir prints do resultado visual no navegador.',
    criteria:[{name:'HTML Semântico',w:3},{name:'CSS e Layout',w:3},{name:'JavaScript / Interatividade',w:2},{name:'Responsividade',w:2},{name:'Boas Práticas Web',w:2}] },
  mobile:           { label:'Mobile (App)',            cat:'codigo',      input:'text',
    hint: 'Cole o código do app (React Native, Flutter, Swift, etc.). Pode incluir prints das telas.',
    criteria:[{name:'Lógica e Estrutura',w:3},{name:'Boas Práticas',w:3},{name:'UI e Experiência',w:2},{name:'Performance',w:2},{name:'Documentação',w:1}] },
  banco_dados:      { label:'Banco de Dados / SQL',    cat:'codigo',      input:'text',
    hint: 'Cole as queries SQL ou o schema do banco. Pode incluir prints dos resultados.',
    criteria:[{name:'Modelagem e Estrutura',w:3},{name:'Eficiência das Queries',w:3},{name:'Normalização',w:2},{name:'Índices e Performance',w:2},{name:'Clareza e Documentação',w:1}] },
  shader:           { label:'Shader',                  cat:'codigo',      input:'text',
    hint: 'Cole o código do shader (GLSL, HLSL ou similar). Pode incluir imagem do efeito visual gerado.',
    criteria:[{name:'Efeito Visual Alcançado',w:3},{name:'Lógica do Shader',w:3},{name:'Eficiência (performance)',w:2},{name:'Originalidade',w:2},{name:'Documentação',w:1}] },
  game_dev:         { label:'Game Development',        cat:'codigo',      input:'text',
    hint: 'Cole o código do jogo (Unity C#, Godot, Unreal, etc.). Pode incluir prints do gameplay.',
    criteria:[{name:'Lógica e Arquitetura',w:3},{name:'Mecânicas Implementadas',w:3},{name:'Boas Práticas',w:2},{name:'Performance',w:2},{name:'Documentação',w:1}] },

  // Arquitetura e Engenharia
  arquitetura_img:  { label:'Prancha Arquitetônica',   cat:'arquitetura', input:'imgs',
    hint: 'Envie as pranchas como imagem. Pode incluir múltiplas pranchas (plantas, cortes, fachadas, perspectivas).',
    criteria:[{name:'Clareza da Representação',w:3},{name:'Plantas e Cortes',w:3},{name:'Diagramação e Layout',w:2},{name:'Escala e Cotas',w:2},{name:'Perspectivas',w:2}] },
  bim:              { label:'Projeto BIM',             cat:'arquitetura', input:'img',
    hint: 'Envie prints ou renders do modelo BIM (Revit, ArchiCAD, etc.). Pode incluir plantas e cortes exportados.',
    criteria:[{name:'Modelagem e Precisão',w:3},{name:'Organização do Modelo',w:3},{name:'Compatibilização',w:2},{name:'Documentação Técnica',w:2},{name:'Normas e Padrões',w:2}] },
  maquete:          { label:'Maquete Física',          cat:'arquitetura', input:'imgs',
    hint: 'Envie fotos da maquete de diferentes ângulos para uma avaliação completa da volumetria e acabamento.',
    criteria:[{name:'Precisão e Escala',w:3},{name:'Qualidade do Acabamento',w:3},{name:'Leitura Espacial',w:2},{name:'Uso de Materiais',w:2},{name:'Apresentação',w:2}] },
  maquete_digital:  { label:'Maquete Digital',         cat:'arquitetura', input:'img',
    hint: 'Envie renders ou prints da maquete digital. Pode incluir múltiplos ângulos e vistas.',
    criteria:[{name:'Precisão e Escala',w:3},{name:'Qualidade Visual',w:3},{name:'Leitura Espacial',w:2},{name:'Materiais e Texturas',w:2},{name:'Apresentação',w:2}] },
  desenho_tecnico:  { label:'Desenho Técnico',         cat:'arquitetura', input:'imgs',
    hint: 'Envie o desenho técnico digitalizado ou exportado como imagem. Pode incluir múltiplas pranchas.',
    criteria:[{name:'Precisão das Cotas',w:3},{name:'Normas Técnicas (ABNT)',w:3},{name:'Clareza da Representação',w:2},{name:'Projeções e Vistas',w:2},{name:'Legenda e Título',w:1}] },
  interiores:       { label:'Design de Interiores',    cat:'arquitetura', input:'img',
    hint: 'Envie renders ou plantas do projeto de interiores. Pode incluir múltiplas perspectivas dos ambientes.',
    criteria:[{name:'Funcionalidade e Circulação',w:3},{name:'Estética e Conceito',w:3},{name:'Escolha de Materiais',w:2},{name:'Iluminação',w:2},{name:'Apresentação',w:2}] },
  paisagismo:       { label:'Paisagismo',              cat:'arquitetura', input:'img',
    hint: 'Envie plantas ou perspectivas do projeto paisagístico. Pode incluir detalhes de espécies e materiais.',
    criteria:[{name:'Conceito e Partido',w:3},{name:'Escolha da Vegetação',w:3},{name:'Funcionalidade',w:2},{name:'Sustentabilidade',w:2},{name:'Apresentação',w:2}] },
  engenharia_civil: { label:'Engenharia Civil',        cat:'arquitetura', input:'imgs',
    hint: 'Envie as pranchas ou cálculos como imagem. Pode incluir estrutural, hidráulica, elétrica, etc.',
    criteria:[{name:'Corretude Técnica',w:3},{name:'Normas e Padrões',w:3},{name:'Clareza da Documentação',w:2},{name:'Detalhamento',w:2},{name:'Viabilidade',w:2}] },

  // Arte e Artesanato
  pintura:          { label:'Pintura / Desenho',       cat:'arte',        input:'img',
    hint: 'Envie foto da obra em boa resolução. Pode incluir detalhes e processo de criação.',
    criteria:[{name:'Técnica e Habilidade',w:3},{name:'Composição',w:3},{name:'Uso de Cor e Luz',w:2},{name:'Expressividade',w:2},{name:'Acabamento',w:2}] },
  escultura:        { label:'Escultura',               cat:'arte',        input:'imgs',
    hint: 'Envie fotos da escultura de diferentes ângulos para uma avaliação completa da forma e acabamento.',
    criteria:[{name:'Forma e Volume',w:3},{name:'Técnica e Execução',w:3},{name:'Acabamento da Superfície',w:2},{name:'Expressividade',w:2},{name:'Uso do Material',w:2}] },
  ceramica:         { label:'Cerâmica / Artesanato',   cat:'arte',        input:'imgs',
    hint: 'Envie fotos da peça de diferentes ângulos. Pode incluir detalhes de acabamento e esmaltação.',
    criteria:[{name:'Forma e Proporção',w:3},{name:'Técnica de Construção',w:3},{name:'Acabamento e Esmaltação',w:2},{name:'Funcionalidade',w:2},{name:'Expressividade',w:2}] },
  gravura:          { label:'Gravura / Serigrafia',    cat:'arte',        input:'img',
    hint: 'Envie foto da estampa finalizada em boa resolução. Pode incluir a matriz se relevante.',
    criteria:[{name:'Qualidade da Matriz',w:3},{name:'Limpeza da Impressão',w:3},{name:'Composição',w:2},{name:'Uso do Contraste',w:2},{name:'Acabamento',w:2}] },
  arte_textil:      { label:'Arte Têxtil',             cat:'arte',        input:'imgs',
    hint: 'Envie fotos da peça têxtil. Pode incluir detalhes de pontos, tramas e acabamentos.',
    criteria:[{name:'Técnica de Execução',w:3},{name:'Qualidade do Acabamento',w:3},{name:'Composição e Design',w:2},{name:'Uso de Materiais',w:2},{name:'Criatividade',w:2}] },

  // Educação Física e Saúde
  exercicio:        { label:'Execução de Exercício',   cat:'saude',       input:'video',
    hint: 'Envie o vídeo da execução do exercício. A IA avalia postura, técnica, amplitude de movimento e segurança.',
    criteria:[{name:'Postura e Alinhamento',w:3},{name:'Técnica de Execução',w:3},{name:'Amplitude de Movimento',w:2},{name:'Controle e Estabilidade',w:2},{name:'Segurança',w:2}] },
  danca:            { label:'Dança / Coreografia',     cat:'saude',       input:'video',
    hint: 'Envie o vídeo da apresentação ou coreografia completa. A IA analisa técnica, expressividade e musicalidade.',
    criteria:[{name:'Técnica e Habilidade',w:3},{name:'Expressividade',w:3},{name:'Musicalidade e Ritmo',w:2},{name:'Sincronia (se em grupo)',w:2},{name:'Presença Cênica',w:2}] },
  tecnica_esportiva:{ label:'Técnica Esportiva',       cat:'saude',       input:'video',
    hint: 'Envie o vídeo da execução técnica (arremesso, chute, nado, etc.). A IA avalia biomecânica e eficiência do movimento.',
    criteria:[{name:'Biomecânica do Movimento',w:3},{name:'Técnica Específica do Esporte',w:3},{name:'Eficiência',w:2},{name:'Velocidade e Potência',w:2},{name:'Consistência',w:2}] },

  // Línguas e Acessibilidade
  libras:           { label:'Libras',                  cat:'linguas',     input:'video',
    hint: 'Envie o vídeo da sinalização (MP4, MOV). A IA analisa configuração de mão, movimento, expressão facial e fluência.',
    criteria:[{name:'Configuração de Mão',w:3},{name:'Movimento e Trajetória',w:3},{name:'Expressão Facial e Corporal',w:3},{name:'Fluência',w:2},{name:'Precisão dos Sinais',w:2}] },
  traducao:         { label:'Tradução / Interpretação',cat:'linguas',     input:'text',
    hint: 'Cole o texto traduzido e o original para comparação. Pode incluir contexto do material.',
    criteria:[{name:'Fidelidade ao Original',w:3},{name:'Naturalidade na Língua Alvo',w:3},{name:'Gramática e Ortografia',w:2},{name:'Vocabulário e Registro',w:2},{name:'Coesão Textual',w:2}] },
  producao_oral:    { label:'Produção Oral (LE)',       cat:'linguas',     input:'video',
    hint: 'Envie o vídeo (MP4, MOV) ou apenas o áudio (MP3, WAV, M4A) da produção oral. A IA avalia pronúncia, fluência e gramática.',
    criteria:[{name:'Pronúncia e Entonação',w:3},{name:'Fluência',w:3},{name:'Gramática',w:2},{name:'Vocabulário',w:2},{name:'Adequação Comunicativa',w:2}] },

  // Outros
  produto:          { label:'Design de Produto',       cat:'outros',      input:'img',
    hint: 'Envie renders ou fotos do produto. Inclua diferentes vistas (frontal, lateral, perspectiva) para avaliação completa.',
    criteria:[{name:'Funcionalidade',w:3},{name:'Ergonomia',w:3},{name:'Estética e Forma',w:2},{name:'Materiais e Produção',w:2},{name:'Inovação',w:2}] },
  gastronomia:      { label:'Gastronomia',             cat:'outros',      input:'imgs',
    hint: 'Envie fotos do prato finalizado (apresentação, emplatamento, detalhes). Pode incluir ficha técnica como arquivo adicional.',
    criteria:[{name:'Apresentação e Emplatamento',w:3},{name:'Técnica Culinária',w:3},{name:'Criatividade',w:2},{name:'Harmonia de Ingredientes',w:2},{name:'Higiene e Organização',w:1}] },
  projeto_interdisciplinar:{ label:'Proj. Interdisciplinar', cat:'outros', input:'text',
    hint: 'Cole o texto do projeto ou envie como .docx. Pode incluir imagens, diagramas ou protótipos como arquivos adicionais.',
    criteria:[{name:'Integração das Disciplinas',w:3},{name:'Desenvolvimento do Tema',w:3},{name:'Metodologia',w:2},{name:'Resultados e Conclusões',w:2},{name:'Apresentação',w:2}] },
};

export const PLANS = {
  gratuito: {
    id: 'gratuito',
    label: 'Gratuito',
    price: 0,
    priceLabel: 'R$ 0/mês',
    color: '#6b7280',
    limits: {
      avaliacoes: 5,
      perfis: 1,
      exercicios: 3,       // null = ilimitado
      relatorios: 0,
      chatbot: 0,
    },
    features: {
      avaliacaoIndividual: true,
      avaliacaoLote: false,
      tomDeProfessor: true,
      criteriosCustom: true,
      edicaoAntesPDF: true,
      pdfIndividual: true,
      exportCSV: false,
      relatorioAluno: false,
      relatorioTurma: false,
      historicoCompleto: true,
      filtrosAvancados: false,
      chatbot: false,
      multiplosPerfisProfessor: false,
      exerciciosReutilizaveis: true,
      exerciciosIlimitados: false,
      suportePrioritario: false,
    },
  },

  essencial: {
    id: 'essencial',
    label: 'Essencial',
    price: 29,
    priceLabel: 'R$ 29/mês',
    color: '#2563eb',
    limits: {
      avaliacoes: 120,
      perfis: 3,
      exercicios: null,
      relatorios: 0,
      chatbot: 50,
    },
    features: {
      avaliacaoIndividual: true,
      avaliacaoLote: true,
      tomDeProfessor: true,
      criteriosCustom: true,
      edicaoAntesPDF: true,
      pdfIndividual: true,
      exportCSV: true,
      relatorioAluno: false,
      relatorioTurma: false,
      historicoCompleto: true,
      filtrosAvancados: false,
      chatbot: true,
      multiplosPerfisProfessor: true,
      exerciciosReutilizaveis: true,
      exerciciosIlimitados: true,
      suportePrioritario: false,
    },
  },

  pro: {
    id: 'pro',
    label: 'Pro',
    price: 59,
    priceLabel: 'R$ 59/mês',
    color: '#7c3aed',
    limits: {
      avaliacoes: 300,
      perfis: null,
      exercicios: null,
      relatorios: 10,
      chatbot: 150,
    },
    features: {
      avaliacaoIndividual: true,
      avaliacaoLote: true,
      tomDeProfessor: true,
      criteriosCustom: true,
      edicaoAntesPDF: true,
      pdfIndividual: true,
      exportCSV: true,
      relatorioAluno: true,
      relatorioTurma: true,
      historicoCompleto: true,
      filtrosAvancados: true,
      chatbot: true,
      multiplosPerfisProfessor: true,
      exerciciosReutilizaveis: true,
      exerciciosIlimitados: true,
      suportePrioritario: false,
    },
  },

  premium: {
    id: 'premium',
    label: 'Premium',
    price: 119,
    priceLabel: 'R$ 119/mês',
    color: '#d97706',
    limits: {
      avaliacoes: 600,
      perfis: null,
      exercicios: null,
      relatorios: 30,
      chatbot: 300,
    },
    features: {
      avaliacaoIndividual: true,
      avaliacaoLote: true,
      tomDeProfessor: true,
      criteriosCustom: true,
      edicaoAntesPDF: true,
      pdfIndividual: true,
      exportCSV: true,
      relatorioAluno: true,
      relatorioTurma: true,
      historicoCompleto: true,
      filtrosAvancados: true,
      chatbot: true,
      multiplosPerfisProfessor: true,
      exerciciosReutilizaveis: true,
      exerciciosIlimitados: true,
      suportePrioritario: true,
    },
  },
};

// Pacotes de avaliações extras (não expiram, acumulam em quota_extra)
// Disponível para Essencial, Pro e Premium
export const ADDONS = [
  { id: 'extra_50',  label: '50 avaliações extras',  qty: 50,  price: 15 },
  { id: 'extra_100', label: '100 avaliações extras', qty: 100, price: 25 },
];

// Pacotes de relatórios extras (não expiram, acumulam em quota_relatorios_extra)
// Disponível para Pro e Premium
export const REPORT_ADDONS = [
  { id: 'extra_rel_5',  label: '5 relatórios extras',  qty: 5,  price: 19 },
  { id: 'extra_rel_10', label: '10 relatórios extras', qty: 10, price: 35 },
];

export const TONES = [
  { id:'neutro',       label:'Neutro',       desc:'Direto e equilibrado' },
  { id:'construtivo',  label:'Construtivo',  desc:'Equilibra crítica com sugestões' },
  { id:'encorajador',  label:'Encorajador',  desc:'Valoriza o esforço e motiva' },
  { id:'rigoroso',     label:'Rigoroso',     desc:'Exigente, padrões elevados' },
  { id:'didatico',     label:'Didático',     desc:'Explica o raciocínio de cada ponto' },
  { id:'informal',     label:'Informal',     desc:'Conversa direta e descontraída' },
  { id:'formal',       label:'Formal',       desc:'Parecer acadêmico oficial' },
];

export function scoreToGrade(s) {
  if (s >= 9) return 'A';
  if (s >= 7) return 'B';
  if (s >= 5) return 'C';
  if (s >= 3) return 'D';
  return 'F';
}

export function scoreColor(s) {
  if (s >= 7) return { bg: '#dcfce7', text: '#16a34a' };
  if (s >= 5) return { bg: '#fef9c3', text: '#ca8a04' };
  return { bg: '#fee2e2', text: '#dc2626' };
}
